# Required
host:

# Optional
backupNginxHost:

backend:
  replicas: 2
  image: ghcr.io/ondrejsika/counter
  EXTRA_TEXT: ''
  API_ONLY: '1'
  SLOW_START: '0'

frontend:
  replicas: 2
  image: ghcr.io/ondrejsika/counter-frontend
  FONT_COLOR: 'black'
  BACKGROUND_COLOR: 'white'